# Generated by Django 2.2.5 on 2020-03-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nav2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='nav3',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='nav4',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
